import mongoose, { Schema } from "mongoose";
import { IBooking } from "./../ReuseAbleInterface/newBookingInterfacs";

const BookingSchema = new Schema<IBooking>({
  supplierName: String,
  supplierReference: String,
  bookingDate: String,
  supplierAgentEmail: String,
  bookingUnderBrand: String,
  payingBy: String,
  payingDueDateTime: String,
  fullName: String,
  phoneNumber: String,
  mobileNumber: String,
  customerEmail: String,
  bookingSource: String,
  departureAirport: String,
  destinationAirport: String,
  flightType: String,
  returnType: String,
  flightClass: String,
  economy: Number,
  goingStopover: String,
  returningStopover: String,
  departureDateTime: String,
  airline: String,
  pnr: String,
  pnrExpiryDateTime: String,
  airlineLocator: String,
  flightDetailsCustomer: String,
  flightDetailsSystem1: String,
  flightDetailsSystem2: String,
  bookingNote: String,
  quoteType: String,
  paymentPlan: String,
  basicFare: Number,
  tax: Number,
  apc: Number,
  safi: Number,
  misc: Number,
  adminChargesExtra: Number,
  passengerCategory: String,
  passengerTitle: String,
  firstName: String,
  middleName: String,
  surName: String,
  departureDatePassenger: String,
  salesPrice: Number,
  adminCharges: Number,
});

export const bookingModel = mongoose.model<IBooking>(
    "Booking" , BookingSchema
)