import React, { useState } from 'react';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import {
    faCalendarAlt,
    faClock,
    faCreditCard,
    faUser,
    faPlane,
} from '@fortawesome/free-solid-svg-icons';

const BookingForm = () => {
    // State for all form fields
    const [formData, setFormData] = useState({
        // Booking Details
        supplierName: '',
        supplierReference: '',
        bookingDate: '',
        supplierAgentEmail: '',
        bookingUnderBrand: '',
        // Receipt Details
        payingBy: '',
        payingDueDateTime: '',
        // Customer Contacts
        fullName: '',
        phoneNumber: '',
        mobileNumber: '',
        customerEmail: '',
        bookingSource: '',
        // Flight Details
        departureAirport: '',
        destinationAirport: '',
        flightType: 'GDS*',
        returnType: 'Galileo',
        flightClass: 'Segments*',
        economy: 0,
        goingStopover: 'Direct',
        returningStopover: 'Direct',
        departureDateTime: '',
        airline: '',
        pnr: '',
        pnrExpiryDateTime: '',
        airlineLocator: '',
        // Flight Details Form Customer (textarea)
        flightDetailsCustomer: '',
        // Flight Details For System (two textareas)
        flightDetailsSystem1: '',
        flightDetailsSystem2: '',
        // Booking Note
        bookingNote: '',
        quoteType: '',
        paymentPlan: '',
        // Ticket Cost
        basicFare: 0,
        tax: 0,
        apc: 0,
        safi: 0,
        misc: 0,
        adminChargesExtra: 0,
        // Passenger Details
        passengerCategory: '',
        passengerTitle: '',
        firstName: '',
        middleName: '',
        surName: '',
        departureDatePassenger: '',
        salesPrice: 0,
        adminCharges: 0,
    });

    const handleChange = (e: any) => {
        const { name, value, type } = e.target;
        setFormData((prev) => ({
            ...prev,
            [name]: type === 'number' ? parseFloat(value) || 0 : value,
        }));
    };

    return (
        <div className="mt-4 font-sans w-full">
            {/* Booking Details (existing) */}
            <section className="mb-8 bg-white p-5 rounded-lg">
                <h2 className="text-xl font-semibold mb-4 flex items-center gap-2 text-gray-700">
                    <p>{/* SVG icon for Booking Details */}</p>
                    Booking Details
                </h2>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-x-6 gap-y-4">
                    <div>
                        <label className="block text-sm font-medium text-gray-700 mb-1">
                            Booking Reference No.
                        </label>
                        <p className="text-gray-500 text-sm">Will be generated by system</p>
                    </div>
                    <div>
                        <label className="block text-sm font-medium text-gray-700 mb-1">
                            Supplier Name
                        </label>
                        <select
                            name="supplierName"
                            value={formData.supplierName}
                            onChange={handleChange}
                            className="w-full p-2 border border-gray-300 rounded-md focus:ring-blue-500 focus:border-blue-500"
                        >
                            <option value="">--Select One--</option>
                        </select>
                    </div>
                    <div>
                        <label className="block text-sm font-medium text-gray-700 mb-1">
                            Supplier Reference
                        </label>
                        <input
                            type="text"
                            name="supplierReference"
                            value={formData.supplierReference}
                            onChange={handleChange}
                            placeholder="Enter Supplier's Reference..."
                            className="w-full p-2 border border-gray-300 rounded-md"
                        />
                    </div>
                    <div>
                        <label className="block text-sm font-medium text-gray-700 mb-1">
                            Booking Date
                        </label>
                        <div className="relative">
                            <input
                                type="text"
                                name="bookingDate"
                                value={formData.bookingDate}
                                onChange={handleChange}
                                placeholder="01/01/2026"
                                className="w-full p-2 border border-gray-300 rounded-md pr-10"
                            />
                            <FontAwesomeIcon
                                icon={faCalendarAlt}
                                className="absolute right-3 top-3 text-gray-400"
                            />
                        </div>
                    </div>
                    <div>
                        <label className="block text-sm font-medium text-gray-700 mb-1">
                            Supplier's Agent's Email
                        </label>
                        <input
                            type="email"
                            name="supplierAgentEmail"
                            value={formData.supplierAgentEmail}
                            onChange={handleChange}
                            placeholder="user@faremakers.co.uk"
                            className="w-full p-2 border border-gray-300 rounded-md"
                        />
                    </div>
                    <div>
                        <label className="block text-sm font-medium text-gray-700 mb-1">
                            Booking Under Brand
                        </label>
                        <input
                            type="text"
                            name="bookingUnderBrand"
                            value={formData.bookingUnderBrand}
                            onChange={handleChange}
                            placeholder="Rare Male"
                            className="w-full p-2 border border-gray-300 rounded-md"
                        />
                    </div>
                </div>
            </section>

            {/* Receipt Details (existing) */}
            <section className="mb-8 bg-white p-5 rounded-lg">
                <h2 className="text-xl font-semibold mb-4 flex items-center gap-2 text-gray-700">
                    <p>{/* SVG icon for Receipt */}</p>
                    Receipt Details
                </h2>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-x-6 gap-y-4">
                    <div>
                        <label className="block text-sm font-medium text-gray-700 mb-1">
                            Paying by
                        </label>
                        <select
                            name="payingBy"
                            value={formData.payingBy}
                            onChange={handleChange}
                            className="w-full p-2 border border-gray-300 rounded-md"
                        >
                            <option value="">--Select One--</option>
                        </select>
                    </div>
                    <div>
                        <label className="block text-sm font-medium text-gray-700 mb-1">
                            Paying due Date & Time
                        </label>
                        <div className="relative">
                            <input
                                type="text"
                                name="payingDueDateTime"
                                value={formData.payingDueDateTime}
                                onChange={handleChange}
                                placeholder="01/01/2026 03:22 PM"
                                className="w-full p-2 border border-gray-300 rounded-md pr-10"
                            />
                            <FontAwesomeIcon
                                icon={faClock}
                                className="absolute right-3 top-3 text-gray-400"
                            />
                        </div>
                    </div>
                </div>
            </section>

            {/* Customer Contacts (existing) */}
            <section className="mb-8 bg-white p-5 rounded-lg">
                <h2 className="text-xl font-semibold mb-4 flex items-center gap-2 text-gray-700">
                    <p>{/* SVG icon for Customer */}</p>
                    Customer Contacts
                </h2>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-x-6 gap-y-4">
                    <div>
                        <label className="block text-sm font-medium text-gray-700 mb-1">
                            Full Name
                        </label>
                        <input
                            type="text"
                            name="fullName"
                            value={formData.fullName}
                            onChange={handleChange}
                            placeholder="Enter Full Name..."
                            className="w-full p-2 border border-gray-300 rounded-md"
                        />
                    </div>
                    <div>
                        <label className="block text-sm font-medium text-gray-700 mb-1">
                            Phone Number
                        </label>
                        <input
                            type="tel"
                            name="phoneNumber"
                            value={formData.phoneNumber}
                            onChange={handleChange}
                            placeholder="Enter Line Number..."
                            className="w-full p-2 border border-gray-300 rounded-md"
                        />
                    </div>
                    <div>
                        <label className="block text-sm font-medium text-gray-700 mb-1">
                            Mobile Number
                        </label>
                        <input
                            type="tel"
                            name="mobileNumber"
                            value={formData.mobileNumber}
                            onChange={handleChange}
                            placeholder="Enter Mobile Number..."
                            className="w-full p-2 border border-gray-300 rounded-md"
                        />
                    </div>
                    <div>
                        <label className="block text-sm font-medium text-gray-700 mb-1">
                            Customer's Email
                        </label>
                        <input
                            type="email"
                            name="customerEmail"
                            value={formData.customerEmail}
                            onChange={handleChange}
                            placeholder="Enter Email..."
                            className="w-full p-2 border border-gray-300 rounded-md"
                        />
                    </div>
                    <div>
                        <label className="block text-sm font-medium text-gray-700 mb-1">
                            Booking Source
                        </label>
                        <select
                            name="bookingSource"
                            value={formData.bookingSource}
                            onChange={handleChange}
                            className="w-full p-2 border border-gray-300 rounded-md"
                        >
                            <option value="">--Select One--</option>
                        </select>
                    </div>
                </div>
            </section>

            {/* Flight Details (existing) */}
            <section className="mb-8 bg-white p-5 rounded-lg">
                <h2 className="text-xl font-semibold mb-4 flex items-center gap-2 text-gray-700">
                    <p>{/* SVG icon for Flight */}</p>
                    Flight Details
                </h2>
                <div className="space-y-4">
                    {/* Departure & Destination */}
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-x-6 gap-y-4">
                        <div>
                            <label className="block text-sm font-medium text-gray-700 mb-1">
                                Departure Airport
                            </label>
                            <input
                                type="text"
                                name="departureAirport"
                                value={formData.departureAirport}
                                onChange={handleChange}
                                placeholder="Enter Departure Airport..."
                                className="w-full p-2 border border-gray-300 rounded-md"
                            />
                        </div>
                        <div>
                            <label className="block text-sm font-medium text-gray-700 mb-1">
                                Destination Airport
                            </label>
                            <input
                                type="text"
                                name="destinationAirport"
                                value={formData.destinationAirport}
                                onChange={handleChange}
                                placeholder="Enter Destination Airport..."
                                className="w-full p-2 border border-gray-300 rounded-md"
                            />
                        </div>
                    </div>

                    {/* Flight Type & Return */}
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-x-6 gap-y-4">
                        <div>
                            <label className="block text-sm font-medium text-gray-700 mb-1">
                                Flight Type
                            </label>
                            <input
                                type="text"
                                name="flightType"
                                value={formData.flightType}
                                readOnly
                                className="w-full p-2 border border-gray-300 rounded-md bg-gray-100"
                            />
                        </div>
                        <div>
                            <label className="block text-sm font-medium text-gray-700 mb-1">
                                Return
                            </label>
                            <input
                                type="text"
                                name="returnType"
                                value={formData.returnType}
                                readOnly
                                className="w-full p-2 border border-gray-300 rounded-md bg-gray-100"
                            />
                        </div>
                    </div>

                    {/* Flight Class & Economy */}
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-x-6 gap-y-4">
                        <div>
                            <label className="block text-sm font-medium text-gray-700 mb-1">
                                Flight Class
                            </label>
                            <input
                                type="text"
                                name="flightClass"
                                value={formData.flightClass}
                                readOnly
                                className="w-full p-2 border border-gray-300 rounded-md bg-gray-100"
                            />
                        </div>
                        <div>
                            <label className="block text-sm font-medium text-gray-700 mb-1">
                                Economy
                            </label>
                            <input
                                type="number"
                                name="economy"
                                value={formData.economy}
                                onChange={handleChange}
                                className="w-full p-2 border border-gray-300 rounded-md"
                            />
                        </div>
                    </div>

                    {/* Going Stopover & Returning Stopover */}
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-x-6 gap-y-4">
                        <div>
                            <label className="block text-sm font-medium text-gray-700 mb-1">
                                Going Stopover
                            </label>
                            <input
                                type="text"
                                name="goingStopover"
                                value={formData.goingStopover}
                                readOnly
                                className="w-full p-2 border border-gray-300 rounded-md bg-gray-100"
                            />
                        </div>
                        <div>
                            <label className="block text-sm font-medium text-gray-700 mb-1">
                                Returning Stopover*
                            </label>
                            <input
                                type="text"
                                name="returningStopover"
                                value={formData.returningStopover}
                                readOnly
                                className="w-full p-2 border border-gray-300 rounded-md bg-gray-100"
                            />
                        </div>
                    </div>

                    {/* Departure Date and Time */}
                    <div>
                        <label className="block text-sm font-medium text-gray-700 mb-1">
                            Departure Date and Time
                        </label>
                        <div className="relative">
                            <input
                                type="text"
                                name="departureDateTime"
                                value={formData.departureDateTime}
                                onChange={handleChange}
                                placeholder="mm/dd/yyyy --:--"
                                className="w-full p-2 border border-gray-300 rounded-md pr-10"
                            />
                            <FontAwesomeIcon
                                icon={faCalendarAlt}
                                className="absolute right-3 top-3 text-gray-400"
                            />
                        </div>
                    </div>

                    {/* Airline & PNR */}
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-x-6 gap-y-4">
                        <div>
                            <label className="block text-sm font-medium text-gray-700 mb-1">
                                Airline
                            </label>
                            <input
                                type="text"
                                name="airline"
                                value={formData.airline}
                                onChange={handleChange}
                                placeholder="Enter Airline..."
                                className="w-full p-2 border border-gray-300 rounded-md"
                            />
                        </div>
                        <div>
                            <label className="block text-sm font-medium text-gray-700 mb-1">
                                PNR*
                            </label>
                            <input
                                type="text"
                                name="pnr"
                                value={formData.pnr}
                                onChange={handleChange}
                                placeholder="Enter PNR..."
                                className="w-full p-2 border border-gray-300 rounded-md"
                            />
                        </div>
                    </div>

                    {/* PNR Expiry Date & Time */}
                    <div>
                        <label className="block text-sm font-medium text-gray-700 mb-1">
                            PNR Expiry Date & Time
                        </label>
                        <div className="relative">
                            <input
                                type="text"
                                name="pnrExpiryDateTime"
                                value={formData.pnrExpiryDateTime}
                                onChange={handleChange}
                                placeholder="mm/dd/yyyy --:--"
                                className="w-full p-2 border border-gray-300 rounded-md pr-10"
                            />
                            <FontAwesomeIcon
                                icon={faClock}
                                className="absolute right-3 top-3 text-gray-400"
                            />
                        </div>
                    </div>

                    {/* Airline Locator */}
                    <div>
                        <label className="block text-sm font-medium text-gray-700 mb-1">
                            Airline Locator
                        </label>
                        <input
                            type="text"
                            name="airlineLocator"
                            value={formData.airlineLocator}
                            onChange={handleChange}
                            placeholder="Airline Locator..."
                            className="w-full p-2 border border-gray-300 rounded-md"
                        />
                    </div>
                </div>
            </section>

            {/* Flight Details form Customer (existing textarea) */}
            <section className="mb-8 bg-white p-5 rounded-lg">
                <h2 className="text-xl font-semibold mb-4 flex items-center gap-2 text-gray-700">
                    Flight Details form Customer
                </h2>
                <div>
                    <textarea
                        name="flightDetailsCustomer"
                        value={formData.flightDetailsCustomer}
                        onChange={handleChange}
                        placeholder="Write a Message"
                        className="w-full h-64 outline-none p-2 border border-gray-300 rounded-md"
                    />
                </div>
            </section>

            {/* Flight Details For System * (first) */}
            <section className="mb-8 bg-white p-5 rounded-lg">
                <h2 className="text-xl font-semibold mb-4 flex items-center gap-2 text-gray-700">
                    Flight Details For System *
                </h2>
                <div>
                    <textarea
                        name="flightDetailsSystem1"
                        value={formData.flightDetailsSystem1}
                        onChange={handleChange}
                        placeholder="Write a Message"
                        className="w-full h-64 outline-none p-2 border border-gray-300 rounded-md"
                    />
                </div>
            </section>

            {/* NEW SECTIONS - Booking Note, Ticket Cost, Passenger Details, and Buttons */}

            {/* Booking Note */}
            <section className="mb-8 bg-white p-5 rounded-lg">
                <h2 className="text-xl font-semibold mb-4 text-gray-800">Booking Note</h2>
                <div className="space-y-4 flex gap-5">
                    <div className='w-6/12'>
                        <label className="block text-sm font-medium text-gray-700 mb-2">
                            Booking Note: <span className="text-red-500">*</span>
                        </label>
                        <textarea
                            name="bookingNote"
                            rows={4}
                            placeholder="Enter your booking note..."
                            value={formData.bookingNote}
                            onChange={handleChange}
                            className="w-full p-3 border border-gray-300 rounded-md focus:ring-blue-500 focus:border-blue-500"
                        />
                    </div>

                    <div className='w-6/12'>
                        <label className="block text-sm font-medium text-gray-700 mb-2">
                            Quote Type: <span className="text-red-500">*</span>
                        </label>
                        <div className="space-y-2 ml-4">
                            {[
                                'Not under quoted',
                                'Under quoted with availability',
                                'Under quoted with non availability',
                            ].map((option) => (
                                <label key={option} className="flex items-center space-x-3">
                                    <input
                                        type="radio"
                                        name="quoteType"
                                        value={option}
                                        checked={formData.quoteType === option}
                                        onChange={handleChange}
                                        className="w-4 h-4 text-blue-600"
                                    />
                                    <span className="text-gray-700">{option}</span>
                                </label>
                            ))}
                        </div>

                        <div>
                            <label className="block text-sm font-medium text-gray-700 mb-2">
                                Payment Plan: <span className="text-red-500">*</span>
                            </label>
                            <div className="space-y-2 ml-4">
                                {['Full Payment', 'On Installment'].map((option) => (
                                    <label key={option} className="flex items-center space-x-3">
                                        <input
                                            type="radio"
                                            name="paymentPlan"
                                            value={option}
                                            checked={formData.paymentPlan === option}
                                            onChange={handleChange}
                                            className="w-4 h-4 text-blue-600"
                                        />
                                        <span className="text-gray-700">{option}</span>
                                    </label>
                                ))}
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            {/* Ticket Cost */}
            <section className="mb-8 bg-white w-full p-5 rounded-lg">
                <h2 className="text-xl font-semibold mb-4 text-gray-800">Ticket Cost</h2>
                <div className="grid grid-cols-4 gap-4 mb-2">
                    {['Basic Fare', 'Tax', 'APC', 'SAFI'].map((label) => (
                        <div key={label}>
                            <label className="block text-sm font-medium text-gray-700">
                                {label}(€): <span className="text-red-500">*</span>
                            </label>
                        </div>
                    ))}
                </div>
                <div className="grid grid-cols-4 gap-4 mb-6">
                    <input
                        type="number"
                        name="basicFare"
                        value={formData.basicFare}
                        onChange={handleChange}
                        className="w-full p-2 border border-gray-300 rounded-md"
                    />
                    <input
                        type="number"
                        name="tax"
                        value={formData.tax}
                        onChange={handleChange}
                        className="w-full p-2 border border-gray-300 rounded-md"
                    />
                    <input
                        type="number"
                        name="apc"
                        value={formData.apc}
                        onChange={handleChange}
                        className="w-full p-2 border border-gray-300 rounded-md"
                    />
                    <input
                        type="number"
                        name="safi"
                        value={formData.safi}
                        onChange={handleChange}
                        className="w-full p-2 border border-gray-300 rounded-md"
                    />
                </div>

                <div className='flex gap-3 items-center'>
                    <div className="w-6/12">
                        <label className="block text-sm font-medium text-gray-700">
                            Misc(€): <span className="text-red-500">*</span>
                        </label>
                        <input
                            type="number"
                            name="misc"
                            value={formData.misc}
                            onChange={handleChange}
                            className="w-full p-2 border border-gray-300 rounded-md"
                            placeholder="Misc"
                        />
                    </div>
                    <div className="w-6/12">


                        <p className="text-xs text-gray-500 ">Admin Charges Extra etc.</p>
                        <input
                            type="number"
                            name="adminChargesExtra"
                            value={formData.adminChargesExtra}
                            onChange={handleChange}
                            className="w-full p-2 border border-gray-300 rounded-md"
                            placeholder="Admin Charges Extra"
                        />
                    </div>
                </div>
            </section>

            {/* Passenger Details */}
            <section className="mb-8 bg-white p-5 rounded-lg">
                <h2 className="text-xl font-semibold mb-4 text-gray-800">
                    Passenger Details <span className="text-sm font-normal text-red-500">*</span>
                </h2>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                    <div>
                        <label className="block text-sm font-medium text-gray-700 mb-1">
                            Category <span className="text-red-500">*</span>
                        </label>
                        <select
                            name="passengerCategory"
                            value={formData.passengerCategory}
                            onChange={handleChange}
                            className="w-full p-2 border border-gray-300 rounded-md"
                        >
                            <option value="">--Select One--</option>
                            <option value="adult">Adult</option>
                            <option value="child">Child</option>
                            <option value="infant">Infant</option>
                        </select>
                    </div>
                    <div>
                        <label className="block text-sm font-medium text-gray-700 mb-1">
                            Title <span className="text-red-500">*</span>
                        </label>
                        <select
                            name="passengerTitle"
                            value={formData.passengerTitle}
                            onChange={handleChange}
                            className="w-full p-2 border border-gray-300 rounded-md"
                        >
                            <option value="">--Select One--</option>
                            <option value="mr">Mr</option>
                            <option value="ms">Ms</option>
                            <option value="mrs">Mrs</option>
                        </select>
                    </div>
                    <div>
                        <label className="block text-sm font-medium text-gray-700 mb-1">
                            First Name <span className="text-red-500">*</span>
                        </label>
                        <div className="relative">
                            <input
                                type="text"
                                name="firstName"
                                placeholder="Enter First Name..."
                                value={formData.firstName}
                                onChange={handleChange}
                                className="w-full p-2 border border-gray-300 rounded-md pl-8"
                            />
                            <span className="absolute left-2 top-2 text-gray-400">☑</span>
                        </div>
                    </div>
                    <div>
                        <label className="block text-sm font-medium text-gray-700 mb-1">
                            Middle Name <span className="text-red-500">*</span>
                        </label>
                        <div className="relative">
                            <input
                                type="text"
                                name="middleName"
                                placeholder="Enter Middle Name..."
                                value={formData.middleName}
                                onChange={handleChange}
                                className="w-full p-2 border border-gray-300 rounded-md pl-8"
                            />
                            <span className="absolute left-2 top-2 text-gray-400">☑</span>
                        </div>
                    </div>
                    <div>
                        <label className="block text-sm font-medium text-gray-700 mb-1">
                            Sur Name <span className="text-red-500">*</span>
                        </label>
                        <div className="relative">
                            <input
                                type="text"
                                name="surName"
                                placeholder="Enter Sur Name..."
                                value={formData.surName}
                                onChange={handleChange}
                                className="w-full p-2 border border-gray-300 rounded-md pl-8"
                            />
                            <span className="absolute left-2 top-2 text-gray-400">☑</span>
                        </div>
                    </div>
                    <div>
                        <label className="block text-sm font-medium text-gray-700 mb-1">
                            Departure Date and Time <span className="text-red-500">*</span>
                        </label>
                        <div className="relative">
                            <input
                                type="text"
                                name="departureDatePassenger"
                                placeholder="mm/dd/yyyy ---"
                                value={formData.departureDatePassenger}
                                onChange={handleChange}
                                className="w-full p-2 border border-gray-300 rounded-md pl-8"
                            />
                            <FontAwesomeIcon icon={faCalendarAlt} className="absolute left-2 top-3 text-gray-400" />
                        </div>
                    </div>
                    <div>
                        <label className="block text-sm font-medium text-gray-700 mb-1">
                            Sales Price <span className="text-red-500">*</span>
                        </label>
                        <input
                            type="number"
                            name="salesPrice"
                            value={formData.salesPrice}
                            onChange={handleChange}
                            className="w-full p-2 border border-gray-300 rounded-md"
                        />
                    </div>
                    <div>
                        <label className="block text-sm font-medium text-gray-700 mb-1">
                            Admin Charges
                        </label>
                        <input
                            type="number"
                            name="adminCharges"
                            value={formData.adminCharges}
                            onChange={handleChange}
                            className="w-full p-2 border border-gray-300 rounded-md"
                        />
                    </div>
                </div>


                {/* Add Button */}
                <div className="my-6">
                    <button className="px-4 py-2 flex gap-2 w-1/12 justify-center items-center bg-[#3B82F6] text-white rounded-md hover:bg-blue-700 transition-colors">
                        <p>
                            <svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
                                <path d="M16.6667 11.6663H11.6667V16.6663H8.33334V11.6663H3.33334V8.33301H8.33334V3.33301H11.6667V8.33301H16.6667V11.6663Z" fill="white" />
                            </svg>

                        </p>
                        Add
                    </button>
                </div>
            </section>

            {/* Action Buttons */}
            <div className="flex justify-end gap-4 bg-white p-6 rounded-lg">
                <button className="px-6 py-2 border border-gray-300 rounded-md text-gray-700 hover:bg-gray-50 transition-colors">
                    Cancel
                </button>
                <button className="px-6 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 transition-colors">
                    Save Booking
                </button>
            </div>
        </div>
    );
};

export default BookingForm;